<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20230625152806 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Data';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql("INSERT INTO `crop` (`id`, `owner_id`, `crop_name`, `fad`, `max_root_depth`, `harvested_green`, `stages`, `sow_depth`) VALUES (1, NULL, 'Wheat', '0.09', '1.8', 1, '{\"A\": {\"KcMin\": 0.35, \"KcMax\": 0.35, \"length\": 15},\"B\": {\"KcMin\": 0.35, \"KcMax\": 1.15, \"length\": 28},\"C\": {\"KcMin\": 1.15, \"KcMax\": 1.15, \"length\": 58},\"D\": {\"KcMin\": 0.45, \"KcMax\": 1.15, \"length\": 35}}', '0.0375')");
        $this->addSql("INSERT INTO `crop` (`id`, `owner_id`, `crop_name`, `fad`, `max_root_depth`, `harvested_green`, `stages`, `sow_depth`) VALUES (2, NULL, 'Bean green', '0.11', '0.7', 1, '{\"A\": {\"KcMin\": 0.35, \"KcMax\": 0.35, \"length\": 18},\"B\": {\"KcMin\": 0.35, \"KcMax\": 1.10, \"length\": 28},\"C\": {\"KcMin\": 1.10, \"KcMax\": 1.10, \"length\": 28},\"D\": {\"KcMin\": 0.9, \"KcMax\": 1.10, \"length\": 10}}', '0.0315')");
        $this->addSql("INSERT INTO `crop` (`id`, `owner_id`, `crop_name`, `fad`, `max_root_depth`, `harvested_green`, `stages`, `sow_depth`) VALUES (3, NULL, 'Cabbage', '0.11', '0.8', 1, '{\"A\": {\"KcMin\": 0.45, \"KcMax\": 0.45, \"length\": 23},\"B\": {\"KcMin\": 0.45, \"KcMax\": 1.05, \"length\": 28},\"C\": {\"KcMin\": 1.05, \"KcMax\": 1.05, \"length\": 63},\"D\": {\"KcMin\": 0.9, \"KcMax\": 1.05, \"length\": 18}}', '0.0095')");
        $this->addSql("INSERT INTO `crop` (`id`, `owner_id`, `crop_name`, `fad`, `max_root_depth`, `harvested_green`, `stages`, `sow_depth`) VALUES (4, NULL, 'Carrot', '0.13', '1', 1, '{\"A\": {\"KcMin\": 0.45, \"KcMax\": 0.45, \"length\": 23},\"B\": {\"KcMin\": 0.45, \"KcMax\": 1.05, \"length\": 33},\"C\": {\"KcMin\": 1.05, \"KcMax\": 1.05, \"length\": 50},\"D\": {\"KcMin\": 0.9, \"KcMax\": 1.05, \"length\": 20}}', '0.0095')");
        $this->addSql("INSERT INTO `crop` (`id`, `owner_id`, `crop_name`, `fad`, `max_root_depth`, `harvested_green`, `stages`, `sow_depth`) VALUES (5, NULL, 'Cucumber', '0.1', '1.2', 1, '{\"A\": {\"KcMin\": 0.45, \"KcMax\": 0.45, \"length\": 23},\"B\": {\"KcMin\": 0.45, \"KcMax\": 0.9, \"length\": 33},\"C\": {\"KcMin\": 0.9, \"KcMax\": 0.9, \"length\": 45},\"D\": {\"KcMin\": 0.75, \"KcMax\": 0.9, \"length\": 18}}', '0.019')");
        $this->addSql("INSERT INTO `crop` (`id`, `owner_id`, `crop_name`, `fad`, `max_root_depth`, `harvested_green`, `stages`, `sow_depth`) VALUES (6, NULL, 'Eggplant', '0.11', '1.2', 1, '{\"A\": {\"KcMin\": 0.45, \"KcMax\": 0.45, \"length\": 30},\"B\": {\"KcMin\": 0.45, \"KcMax\": 1.15, \"length\": 40},\"C\": {\"KcMin\": 1.15, \"KcMax\": 1.15, \"length\": 43},\"D\": {\"KcMin\": 0.8, \"KcMax\": 1.15, \"length\": 23}}', '0.0095')");
        $this->addSql("INSERT INTO `crop` (`id`, `owner_id`, `crop_name`, `fad`, `max_root_depth`, `harvested_green`, `stages`, `sow_depth`) VALUES (8, NULL, 'Lettuce', '0.14', '0.5', 1, '{\"A\": {\"KcMin\": 0.45, \"KcMax\": 0.45, \"length\": 28},\"B\": {\"KcMin\": 0.45, \"KcMax\": 1, \"length\": 40},\"C\": {\"KcMin\": 1, \"KcMax\": 1, \"length\": 30},\"D\": {\"KcMin\": 0.9, \"KcMax\": 1, \"length\": 10}}', '0.0045')");
        $this->addSql("INSERT INTO `crop` (`id`, `owner_id`, `crop_name`, `fad`, `max_root_depth`, `harvested_green`, `stages`, `sow_depth`) VALUES (9, NULL, 'Maize(Sweet)', '0.1', '1.2', 1, '{\"A\": {\"KcMin\": 0.4, \"KcMax\": 0.4, \"length\": 20}, \"B\": {\"KcMin\": 0.4, \"KcMax\": 1.15, \"length\": 28}, \"C\": {\"KcMin\": 1.15, \"KcMax\": 1.15, \"length\": 38}, \"D\": {\"KcMin\": 1, \"KcMax\": 1.15, \"length\": 10}}', '0.0375')");
        $this->addSql("INSERT INTO `crop` (`id`, `owner_id`, `crop_name`, `fad`, `max_root_depth`, `harvested_green`, `stages`, `sow_depth`) VALUES (10, NULL, 'Maize(grain)', '0.09', '1.7', 0, '{\"A\": {\"KcMin\": 0.4, \"KcMax\": 0.4, \"length\": 25}, \"B\": {\"KcMin\": 0.4, \"KcMax\": 1.15, \"length\": 43}, \"C\": {\"KcMin\": 1.15, \"KcMax\": 1.15, \"length\": 50}, \"D\": {\"KcMin\": 0.7, \"KcMax\": 1.15, \"length\": 35}}', '0.0375')");
        $this->addSql("INSERT INTO `crop` (`id`, `owner_id`, `crop_name`, `fad`, `max_root_depth`, `harvested_green`, `stages`, `sow_depth`) VALUES (11, NULL, 'Melon', '0.11', '1.5', 1, '{\"A\": {\"KcMin\": 0.45, \"KcMax\": 0.45, \"length\": 28}, \"B\": {\"KcMin\": 0.45, \"KcMax\": 1, \"length\": 40}, \"C\": {\"KcMin\": 1, \"KcMax\": 1, \"length\": 53}, \"D\": {\"KcMin\": 0.75, \"KcMax\": 1, \"length\": 20}}', '0.0375')");
        $this->addSql("INSERT INTO `crop` (`id`, `owner_id`, `crop_name`, `fad`, `max_root_depth`, `harvested_green`, `stages`, `sow_depth`) VALUES (12, NULL, 'Onion(green)', '0.14', '0.8', 1, '{\"A\": {\"KcMin\": 0.5, \"KcMax\": 0.5, \"length\": 25},\"B\": {\"KcMin\": 0.5, \"KcMax\": 1, \"length\": 35},\"C\": {\"KcMin\": 1, \"KcMax\": 1, \"length\": 15},\"D\": {\"KcMin\": 1, \"KcMax\": 1, \"length\": 8}}', '0.0095')");
        $this->addSql("INSERT INTO `crop` (`id`, `owner_id`, `crop_name`, `fad`, `max_root_depth`, `harvested_green`, `stages`, `sow_depth`) VALUES (13, NULL, 'Peas', '0.12', '1', 1, '{\"A\": {\"KcMin\": 0.45, \"KcMax\": 0.45, \"length\": 18},\"B\": {\"KcMin\": 0.45, \"KcMax\": 1.15, \"length\": 28},\"C\": {\"KcMin\": 1.15, \"KcMax\": 1.15, \"length\": 35},\"D\": {\"KcMin\": 1.05, \"KcMax\": 1.15, \"length\": 15}}', '0.0375')");
        $this->addSql("INSERT INTO `crop` (`id`, `owner_id`, `crop_name`, `fad`, `max_root_depth`, `harvested_green`, `stages`, `sow_depth`) VALUES (14, NULL, 'Bell Pepper', '0.14', '1', 1, '{\"A\": {\"KcMin\": 0.35, \"KcMax\": 0.35, \"length\": 28},\"B\": {\"KcMin\": 0.35, \"KcMax\": 1.05, \"length\": 38},\"C\": {\"KcMin\": 1.05, \"KcMax\": 1.05, \"length\": 75},\"D\": {\"KcMin\": 0.9, \"KcMax\": 1.05, \"length\": 25}}', '0.0095')");
        $this->addSql("INSERT INTO `crop` (`id`, `owner_id`, `crop_name`, `fad`, `max_root_depth`, `harvested_green`, `stages`, `sow_depth`) VALUES (15, NULL, 'Potato', '0.13', '0.6', 1, '{\"A\": {\"KcMin\": 0.45, \"KcMax\": 0.45, \"length\": 28},\"B\": {\"KcMin\": 0.45, \"KcMax\": 1.15, \"length\": 33},\"C\": {\"KcMin\": 1.15, \"KcMax\": 1.15, \"length\": 40},\"D\": {\"KcMin\": 0.85, \"KcMax\": 1.15, \"length\": 25}}', '0.1015')");
        $this->addSql("INSERT INTO `crop` (`id`, `owner_id`, `crop_name`, `fad`, `max_root_depth`, `harvested_green`, `stages`, `sow_depth`) VALUES (16, NULL, 'Radish', '0.14', '0.5', 1, '{\"A\": {\"KcMin\": 0.45, \"KcMax\": 0.45, \"length\": 8},\"B\": {\"KcMin\": 0.45, \"KcMax\": 0.9, \"length\": 10},\"C\": {\"KcMin\": 0.9, \"KcMax\": 0.9, \"length\": 15},\"D\": {\"KcMin\": 0.9, \"KcMax\": 0.9, \"length\": 5}}', '0.019')");
        $this->addSql("INSERT INTO `crop` (`id`, `owner_id`, `crop_name`, `fad`, `max_root_depth`, `harvested_green`, `stages`, `sow_depth`) VALUES (17, NULL, 'Spinach', '0.16', '0.5', 1, '{\"A\": {\"KcMin\": 0.45, \"KcMax\": 0.45, \"length\": 20},\"B\": {\"KcMin\": 0.45, \"KcMax\": 1, \"length\": 25},\"C\": {\"KcMin\": 1, \"KcMax\": 1, \"length\": 28},\"D\": {\"KcMin\": 0.9, \"KcMax\": 1, \"length\": 8}}', '0.016')");
        $this->addSql("INSERT INTO `crop` (`id`, `owner_id`, `crop_name`, `fad`, `max_root_depth`, `harvested_green`, `stages`, `sow_depth`) VALUES (18, NULL, 'Pumpkin', '0.13', '1.5', 1, '{\"A\": {\"KcMin\": 0.45, \"KcMax\": 0.45, \"length\": 23},\"B\": {\"KcMin\": 0.45, \"KcMax\": 0.9, \"length\": 33},\"C\": {\"KcMin\": 0.9, \"KcMax\": 0.9, \"length\": 33},\"D\": {\"KcMin\": 0.75, \"KcMax\": 0.9, \"length\": 20}}', '0.0375')");
        $this->addSql("INSERT INTO `crop` (`id`, `owner_id`, `crop_name`, `fad`, `max_root_depth`, `harvested_green`, `stages`, `sow_depth`) VALUES (19, NULL, 'Sunflower', '0.11', '1.5', 0, '{\"A\": {\"KcMin\": 0.35, \"KcMax\": 0.35, \"length\": 23},\"B\": {\"KcMin\": 0.35, \"KcMax\": 1.15, \"length\": 35},\"C\": {\"KcMin\": 1.15, \"KcMax\": 1.15, \"length\": 45},\"D\": {\"KcMin\": 0.8, \"KcMax\": 1.15, \"length\": 25}}', '0.0375')");
        $this->addSql("INSERT INTO `crop` (`id`, `owner_id`, `crop_name`, `fad`, `max_root_depth`, `harvested_green`, `stages`, `sow_depth`) VALUES (20, NULL, 'Tomato', '0.12', '1.5', 1, '{\"A\": {\"KcMin\": 0.45, \"KcMax\": 0.45, \"length\": 33},\"B\": {\"KcMin\": 0.45, \"KcMax\": 1.15, \"length\": 43},\"C\": {\"KcMin\": 1.15, \"KcMax\": 1.15, \"length\": 55},\"D\": {\"KcMin\": 0.8, \"KcMax\": 1.15, \"length\": 28}}', '0.0095')");
        $this->addSql("INSERT INTO `crop` (`id`, `owner_id`, `crop_name`, `fad`, `max_root_depth`, `harvested_green`, `stages`, `sow_depth`) VALUES (21, NULL, 'Betroot', '0.1', '1', 1, '{\"A\": {\"KcMin\": 0.5, \"KcMax\": 0.5, \"length\": 10},\"B\": {\"KcMin\": 0.5, \"KcMax\": 1.05, \"length\": 25},\"C\": {\"KcMin\": 1.05, \"KcMax\": 1.05, \"length\": 20},\"D\": {\"KcMin\": 0.95, \"KcMax\": 1.05, \"length\": 10}}', '0.019')");
        $this->addSql("INSERT INTO `crop` (`id`, `owner_id`, `crop_name`, `fad`, `max_root_depth`, `harvested_green`, `stages`, `sow_depth`) VALUES (22, NULL, 'Olives', '0.07', '1.7', 1, '{\"A\": {\"KcMin\": 0.65, \"KcMax\": 0.65, \"length\": 30},\"B\": {\"KcMin\": 0.65, \"KcMax\": 0.7, \"length\": 90},\"C\": {\"KcMin\": 0.7, \"KcMax\": 0.7, \"length\": 60},\"D\": {\"KcMin\": 0.7, \"KcMax\": 0.7, \"length\": 90}}', '0.019')");
        $this->addSql("INSERT INTO `crop` (`id`, `owner_id`, `crop_name`, `fad`, `max_root_depth`, `harvested_green`, `stages`, `sow_depth`) VALUES (23, NULL, 'Citrus', '0.1', '1.5', 1, '{\"A\": {\"KcMin\": 0.4, \"KcMax\": 0.4, \"length\": 60},\"B\": {\"KcMin\": 0.4, \"KcMax\": 0.65, \"length\": 90},\"C\": {\"KcMin\": 0.65, \"KcMax\": 0.65, \"length\": 120},\"D\": {\"KcMin\": 0.65, \"KcMax\": 0.75, \"length\": 95}}', '0.019')");
        $this->addSql("INSERT INTO `crop` (`id`, `owner_id`, `crop_name`, `fad`, `max_root_depth`, `harvested_green`, `stages`, `sow_depth`) VALUES (24, NULL, 'Almonds', '0.12', '2', 0, '{\"A\": {\"KcMin\": 0.35, \"KcMax\": 0.35, \"length\": 25},\"B\": {\"KcMin\": 0.35, \"KcMax\": 1.15, \"length\": 90},\"C\": {\"KcMin\": 1.15, \"KcMax\": 1.15, \"length\": 60},\"D\": {\"KcMin\": 0.65, \"KcMax\": 1.15, \"length\": 60}}', '0.063')");
        $this->addSql("INSERT INTO `crop` (`id`, `owner_id`, `crop_name`, `fad`, `max_root_depth`, `harvested_green`, `stages`, `sow_depth`) VALUES (25, NULL, 'Zucchini', '0.1', '1', 1, '{\"A\": {\"KcMin\": 0.5, \"KcMax\": 0.5, \"length\": 23},\"B\": {\"KcMin\": 0.5, \"KcMax\": 0.975, \"length\": 33},\"C\": {\"KcMin\": 0.975, \"KcMax\": 0.975, \"length\": 25},\"D\": {\"KcMin\": 0.825, \"KcMax\": 0.975, \"length\": 15}}', '0.019')");
        $this->addSql("INSERT INTO `crop` (`id`, `owner_id`, `crop_name`, `fad`, `max_root_depth`, `harvested_green`, `stages`, `sow_depth`) VALUES (26, NULL, 'Garlic', '0.14', '0.5', 0, '{\"A\": {\"KcMin\": 0.6, \"KcMax\": 0.6, \"length\": 23},\"B\": {\"KcMin\": 0.6, \"KcMax\": 1.1, \"length\": 55},\"C\": {\"KcMin\": 1.1, \"KcMax\": 1.1, \"length\": 20},\"D\": {\"KcMin\": 0.875, \"KcMax\": 1.1, \"length\": 30}}', '0.0375')");
        $this->addSql("INSERT INTO `crop` (`id`, `owner_id`, `crop_name`, `fad`, `max_root_depth`, `harvested_green`, `stages`, `sow_depth`) VALUES (27, NULL, 'Artichokes', '0.11', '0.9', 1, '{\"A\": {\"KcMin\": 0.4, \"KcMax\": 0.4, \"length\": 25},\"B\": {\"KcMin\": 0.4, \"KcMax\": 1, \"length\": 65},\"C\": {\"KcMin\": 1, \"KcMax\": 1, \"length\": 80},\"D\": {\"KcMin\": 0.95, \"KcMax\": 1, \"length\": 65}}', '0.0095')");
        $this->addSql("INSERT INTO `crop` (`id`, `owner_id`, `crop_name`, `fad`, `max_root_depth`, `harvested_green`, `stages`, `sow_depth`) VALUES (28, NULL, 'Chilies', '0.14', '0.6', 1, '{\"A\": {\"KcMin\": 0.4, \"KcMax\": 0.4, \"length\": 25},\"B\": {\"KcMin\": 0.4, \"KcMax\": 1, \"length\": 55},\"C\": {\"KcMin\": 1, \"KcMax\": 1, \"length\": 20},\"D\": {\"KcMin\": 0.9, \"KcMax\": 1, \"length\": 30}}', '0.0095')");
        $this->addSql("INSERT INTO `crop` (`id`, `owner_id`, `crop_name`, `fad`, `max_root_depth`, `harvested_green`, `stages`, `sow_depth`) VALUES (29, NULL, 'Broccoli', '0.11', '0.6', 1, '{\"A\": {\"KcMin\": 0.7, \"KcMax\": 0.7, \"length\": 35},\"B\": {\"KcMin\": 0.7, \"KcMax\": 1.05, \"length\": 45},\"C\": {\"KcMin\": 1.05, \"KcMax\": 1.05, \"length\": 40},\"D\": {\"KcMin\": 0.95, \"KcMax\": 1.05, \"length\": 15}}', '0.0095')");
        $this->addSql("INSERT INTO `crop` (`id`, `owner_id`, `crop_name`, `fad`, `max_root_depth`, `harvested_green`, `stages`, `sow_depth`) VALUES (30, NULL, 'Cauliflower', '0.11', '0.7', 1, '{\"A\": {\"KcMin\": 0.7, \"KcMax\": 0.7, \"length\": 35},\"B\": {\"KcMin\": 0.7, \"KcMax\": 1.05, \"length\": 50},\"C\": {\"KcMin\": 1.05, \"KcMax\": 1.05, \"length\": 40},\"D\": {\"KcMin\": 0.95, \"KcMax\": 1.05, \"length\": 15}}', '0.0095')");
        $this->addSql("INSERT INTO `crop` (`id`, `owner_id`, `crop_name`, `fad`, `max_root_depth`, `harvested_green`, `stages`, `sow_depth`) VALUES (31, NULL, 'Apples', '0.1', '2', 1, '{\"A\": {\"KcMin\": 0.5, \"KcMax\": 0.5, \"length\": 40},\"B\": {\"KcMin\": 0.5, \"KcMax\": 1.1, \"length\": 70},\"C\": {\"KcMin\": 1.1, \"KcMax\": 1.1, \"length\": 40},\"D\": {\"KcMin\": 0.75, \"KcMax\": 1.1, \"length\": 40}}', '0.019')");
        $this->addSql("INSERT INTO `crop` (`id`, `owner_id`, `crop_name`, `fad`, `max_root_depth`, `harvested_green`, `stages`, `sow_depth`) VALUES (32, NULL, 'Apricots', '0.1', '1', 1, '{\"A\": {\"KcMin\": 0.4, \"KcMax\": 0.4, \"length\": 33},\"B\": {\"KcMin\": 0.4, \"KcMax\": 1.1, \"length\": 60},\"C\": {\"KcMin\": 1.1, \"KcMax\": 1.1, \"length\": 33},\"D\": {\"KcMin\": 0.65, \"KcMax\": 1.1, \"length\": 25}}', '0.0375')");
        $this->addSql("INSERT INTO `crop` (`id`, `owner_id`, `crop_name`, `fad`, `max_root_depth`, `harvested_green`, `stages`, `sow_depth`) VALUES (33, NULL, 'Watermelon', '0.12', '1.5', 1, '{\"A\": {\"KcMin\": 0.4, \"KcMax\": 0.4, \"length\": 15},\"B\": {\"KcMin\": 0.4, \"KcMax\": 1, \"length\": 25},\"C\": {\"KcMin\": 1, \"KcMax\": 1, \"length\": 25},\"D\": {\"KcMin\": 0.75, \"KcMax\": 1, \"length\": 30}}', '0.0375')");
        $this->addSql("INSERT INTO `crop` (`id`, `owner_id`, `crop_name`, `fad`, `max_root_depth`, `harvested_green`, `stages`, `sow_depth`) VALUES (34, NULL, 'Cherry', '0.1', '2', 1, '{\"A\": {\"KcMin\": 0.4, \"KcMax\": 0.4, \"length\": 35},\"B\": {\"KcMin\": 0.4, \"KcMax\": 1.1, \"length\": 55},\"C\": {\"KcMin\": 1.1, \"KcMax\": 1.1, \"length\": 20},\"D\": {\"KcMin\": 0.75, \"KcMax\": 1.1, \"length\": 18}}', '0.019')");
        $this->addSql("INSERT INTO `crop` (`id`, `owner_id`, `crop_name`, `fad`, `max_root_depth`, `harvested_green`, `stages`, `sow_depth`) VALUES (35, NULL, 'Mint', '0.12', '0.8', 1, '{\"A\": {\"KcMin\": 0.5, \"KcMax\": 0.5, \"length\": 15},\"B\": {\"KcMin\": 0.5, \"KcMax\": 1.15, \"length\": 40},\"C\": {\"KcMin\": 1.15, \"KcMax\": 1.15, \"length\": 35},\"D\": {\"KcMin\": 1.1, \"KcMax\": 1.15, \"length\": 15}}', '0.0095')");
        $this->addSql("INSERT INTO `crop` (`id`, `owner_id`, `crop_name`, `fad`, `max_root_depth`, `harvested_green`, `stages`, `sow_depth`) VALUES (36, NULL, 'Oats', '0.09', '1.5', 0, '{\"A\": {\"KcMin\": 0.35, \"KcMax\": 0.35, \"length\": 15},\"B\": {\"KcMin\": 0.35, \"KcMax\": 1.15, \"length\": 28},\"C\": {\"KcMin\": 1.15, \"KcMax\": 1.15, \"length\": 58},\"D\": {\"KcMin\": 0.45, \"KcMax\": 1.15, \"length\": 35}}', '0.0375')");
        $this->addSql("INSERT INTO `crop` (`id`, `owner_id`, `crop_name`, `fad`, `max_root_depth`, `harvested_green`, `stages`, `sow_depth`) VALUES (37, NULL, 'Rye', '0.08', '2.3', 0, '{\"A\": {\"KcMin\": 0.35, \"KcMax\": 0.35, \"length\": 15},\"B\": {\"KcMin\": 0.35, \"KcMax\": 1.15, \"length\": 28},\"C\": {\"KcMin\": 1.15, \"KcMax\": 1.15, \"length\": 58},\"D\": {\"KcMin\": 0.45, \"KcMax\": 1.15, \"length\": 35}}', '0.0375')");
        $this->addSql("INSERT INTO `soil` (`id`, `type`, `paw`, `depth`, `owner_id`) VALUES (1, 'Heavy', '200', '1', NULL)");
        $this->addSql("INSERT INTO `soil` (`id`, `type`, `paw`, `depth`, `owner_id`) VALUES (2, 'Light', '60', '1', NULL)");
        $this->addSql("INSERT INTO `soil` (`id`, `type`, `paw`, `depth`, `owner_id`) VALUES (3, 'Medium', '290', '1', NULL)");
        $this->addSql("INSERT INTO `soil` (`id`, `type`, `paw`, `depth`, `owner_id`) VALUES (4, 'Black Clay', '200', '1', NULL)");
        $this->addSql("INSERT INTO `soil` (`id`, `type`, `paw`, `depth`, `owner_id`) VALUES (5, 'Red Loamy', '180', '1', NULL)");
        $this->addSql("INSERT INTO `soil` (`id`, `type`, `paw`, `depth`, `owner_id`) VALUES (6, 'Red Sandy Loam', '140', '1', NULL)");
        $this->addSql("INSERT INTO `soil` (`id`, `type`, `paw`, `depth`, `owner_id`) VALUES (7, 'Red Sandy', '100', '1', NULL)");

    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql("DELETE FROM crop");
        $this->addSql("DELETE FROM soil");
    }
}
